### ISSUE TITLE
Merge with my version?

### ISSUE THREAD

**Issue by voidberg** [behzad888/awesome-aurelia#2]
Hey,

I'm also running an awesome aurelia list at https://github.com/voidberg/awesome-aurelia

Want to merge?

Andu

**Comment by behzad888** [comment]
Hey,

Its very good. I'm OK.

**Comment by riddla** [comment]
Let's do so :) After that you should also ping https://github.com/sindresorhus/awesome to update the Aurelia item.

**Comment by behzad888** [comment]
@riddla Aurelia item is added to [sindresorhus/awesome](https://github.com/sindresorhus/awesome#front-end-development)

**Comment by behzad888** [comment]
Since I haven' heard anything back, I'm going to close this.

**Comment by ctjhoa** [comment]
Finally, @behzad888 is it merge with @voidberg version ?
I'm confused, if that's true, could you please add a deprecation note in the deprecated one.
Thanks

**Comment by riddla** [comment]
I'm also comfused. As @voidberg asked to merge in his version and not the other way round ...
We really should join forces here, if @voidberg is ok with it, we could merge the other list in here. But it would be nice if at least @voidberg gets commit rights for the new merged list.

**Comment by voidberg** [comment]
@behzad888 sorry for not answering but some things got in the way and I've been away. Can me and @riddla get access to your repository so that we can merge what we have into yours?

(I am assuming your list would become the main one)

**Comment by behzad888** [comment]
@voidberg Got it

**Comment by voidberg** [comment]
I've created a PR merging my repo.

What do you think about using markdownlint and enforcing a style for the file so that we don't end up with inconsistent PRs? I can setup CI for this like I had on my repo.

**Comment by voidberg** [comment]
Closing this, I've opened up a separate ticket for markdownlint #9.
