### ISSUE TITLE
Add an article about another ACL integration in Aurelia app using CASL

### ISSUE THREAD

**Issue by stalniy** [behzad888/awesome-aurelia#23]
This is the article about authorization in Aurelia app with help of CASL - https://medium.com/@sergiy.stotskiy/casl-based-authorization-in-aurelia-app-3e44c0fe1703

There is also the full example on github - https://github.com/stalniy/casl-aurelia-example

**Comment by behzad888** [comment]
Can you add links about CACL by PR?

**Comment by stalniy** [comment]
done
